### ISSUE TITLE
Feedback on Big Idea!

### ISSUE THREAD

**Issue by PeteTrenk** [w201rdada/portfolio-rahulvas#1]
Hi Rahul,

I like the idea. My take on it is that you want to: develop a word of mouth index to model coin values and make trades against that index. Crypto coins seem like the wild west of trading right now, so there could be a lot of upside with the right approach. Given that crypto currencies are less regulated and popular, it's reasonable to believe that trading on those exchanges isn't as sophisticated as is trading on an equities/bond exchange. So, you could have an angle.  

Your idea reminded me of the VIX index for stocks which attempts to measure market sentiment or something like that. It's apparently a really popular indicator (from what i've read). I'd be curious to know if there are additional, viable social sources you can tap into to monitor trends in sentiment (ie Facebook's Graph API or Google query trends) and which ones are more telling of movements in crypto currencies. I wouldn't have thought that the news media offers API access. really cool.

I like the overall flow and your proposed methodology. I think something to consider, as far as scalability, is whether or not your model, if widely adopted, will influence the actual price of the coin and the resulting predictive capabilities. i think the theory in finance goes something like all known information is reflected in the current price of the asset. So maybe it wouldn't be as effective for gains if everyone was using the model? Either way, I think it makes for a really interesting case and at the very least might help with those student loans :)

**Comment by rahulvas** [comment]
Using Google Trends is genius! I'll definitely include a section about that in the middle. I'll also do more research into Facebook's Graph API since I'm unfamiliar with that. 

Thank you for the feedback!

**Comment by adaraliao** [comment]
Gist: I see this as a great predictive tool for regular investors to easily participate in cryptocurrency trading by measuring sentiment on twitter, news and market price. I think it’s great as it levels the playing field for regular investors and institutional investors who have armies of analysts conducting research and trend analysis, as well as the finances to materially sway prices. The sentiment measurement can alert investors to lesser-known but up-and-coming cryptocurrencies, which can be difficult given the vast numbers of currencies but scant information to separate promising ones from the rest. It is hard to always be watching cryptocurrency movement and news and this service does it for users.

The natural language analysis of tweets and news is strongly relevant to your goal. Given the strong animal spirits in cryptocurrency markets and few other methods of assessing the inherent “worthiness” of the investment (it’s not equity, nor a commodity driven by natural supply), sentiment seems to be the biggest factor deciding prices.

What can be added is broader news coverage, perhaps from Google News headlines API (https://newsapi.org/s/google-news-api). 

From your news analysis, maybe it could be possible to use machine learning to determine what type of events affects cryptocurrency prices the most (some possible events like “regulation”, “hedge fund investment”, “cryptocurrency thieving” come to mind). This could be interesting for the user to know.

As you mentioned, it is important to note to users that loss is very possible. As your project gains reliability and enhanced algorithms, perhaps you can partner with an exchange to offer a stop-loss sell order feature where the price is determined by your sentiment analysis.

Overall, very relevant and useful tool for many curious investors! I would use it and I think other people like me (curious, but no time to read through all the research and news) will find it very helpful.

**Comment by rahulvas** [comment]
Adara, that's a great suggestion! Thank you! I'll add it in :)

**Comment by rahulvas** [comment]
Hey all,
I took your advice to heart about the data sources and incorporated them in my data sources section. 

@adaraliao I do agree that I should keep this secret sauce a secret, and if it becomes a full fledged business, I might just charge for the service ;) 

Thank you both for your input!
